# Render Blueprint Configuration
# Customer AI Driven Feedback Analyzer v3.1.0
# IMPORTANT: Service names must match existing deployments

services:
  # Redis Key-Value Store (MUST BE FIRST for service references)
  - type: keyvalue
    name: feedback-analyzer-redis
    plan: free  # Match existing deployment
    region: oregon
    maxmemoryPolicy: noeviction  # Changed from allkeys-lru for job queue reliability
    ipAllowList: []

  # FastAPI Backend Service (Private)
  - type: pserv
    name: customer-feedback-api  # Match existing deployment name
    runtime: python
    region: oregon
    plan: starter  # Match existing deployment
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api && uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: PORT
        value: 10000
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AI_MODEL
        value: gpt-4o-mini
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: feedback-analyzer-redis
          property: REDIS_URL
      - key: CELERY_BROKER_URL
        fromService:
          type: keyvalue
          name: feedback-analyzer-redis
          property: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: keyvalue
          name: feedback-analyzer-redis
          property: REDIS_URL
      - key: FILE_MAX_MB  # Fixed from MAX_FILE_SIZE_MB
        value: 20
      - key: ALLOWED_EXTENSIONS
        value: "csv,xlsx,xls"
      - key: MAX_BATCH_SIZE
        value: 50
      - key: MAX_RPS
        value: 8
      - key: RESULTS_TTL_SECONDS
        value: 86400
      - key: API_WORKERS
        value: 1
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health  # Fixed from /api/health
    autoDeploy: true
    buildFilter:
      paths:
        - api/**
        - requirements.txt

  # Celery Worker Service (Background Worker)
  - type: worker
    name: celery-worker  # Match existing deployment name
    runtime: python
    region: oregon
    plan: starter  # Match existing deployment
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api && celery -A app.workers.celery_app worker --loglevel=INFO
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: APP_ENV
        value: production
      - key: SECRET_KEY
        fromService:
          type: pserv
          name: customer-feedback-api
          envVarKey: SECRET_KEY
      - key: OPENAI_API_KEY
        sync: false
      - key: AI_MODEL
        value: gpt-4o-mini
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: feedback-analyzer-redis
          property: REDIS_URL
      - key: CELERY_BROKER_URL
        fromService:
          type: keyvalue
          name: feedback-analyzer-redis
          property: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: keyvalue
          name: feedback-analyzer-redis
          property: REDIS_URL
      - key: FILE_MAX_MB
        value: 20
      - key: MAX_BATCH_SIZE
        value: 50
      - key: MAX_RPS
        value: 8
      - key: RESULTS_TTL_SECONDS
        value: 86400
      - key: CELERY_WORKER_CONCURRENCY
        value: 2
      - key: CELERY_MAX_TASKS_PER_CHILD
        value: 100
      - key: LOG_LEVEL
        value: INFO
    autoDeploy: true
    buildFilter:
      paths:
        - api/**
        - requirements.txt

  # BFF/Frontend Service (Public)
  - type: web
    name: customer-feedback-app  # Match existing deployment name
    runtime: node
    region: oregon
    plan: starter  # Match existing deployment
    buildCommand: cd web && npm install && npm run build:render
    startCommand: cd web && npm run start:prod
    # No preDeployCommand needed - build handles everything
    envVars:
      - key: NODE_VERSION
        value: 20.11.0  # Fixed: specific version
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: API_PROXY_TARGET
        fromService:
          type: pserv
          name: customer-feedback-api
          property: hostport  # Use hostport for private service connection
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - web/**
        - package.json
        - package-lock.json

# Note: Routes section removed from web service as it's handled by Express proxy